redis_settings:
  host: 'localhost'
  port: 6379
  password: ''
synchronisation_settings:
  inventories: true
  ender_chests: true
  health: true
  hunger: true
  experience: true
  potion_effects: true
  statistics: true
  game_mode: true
  advancements: true
  location: false
  flight: false
cluster_id: 'main'
check_for_updates: true
native_advancement_synchronization: false